# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class UiMain(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(1120, 724)
        self.backgrond = QtWidgets.QWidget(main)
        self.backgrond.setObjectName("backgrond")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.backgrond)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_layout = QtWidgets.QGridLayout()
        self.button_layout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.button_layout.setSpacing(6)
        self.button_layout.setObjectName("button_layout")
        self.R1C5 = QtWidgets.QPushButton(self.backgrond)
        self.R1C5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R1C5.sizePolicy().hasHeightForWidth())
        self.R1C5.setSizePolicy(sizePolicy)
        self.R1C5.setMinimumSize(QtCore.QSize(50, 50))
        self.R1C5.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.R1C5.setText("")
        self.R1C5.setAutoRepeat(False)
        self.R1C5.setAutoExclusive(False)
        self.R1C5.setAutoDefault(False)
        self.R1C5.setDefault(False)
        self.R1C5.setFlat(False)
        self.R1C5.setObjectName("R1C5")
        self.button_layout.addWidget(self.R1C5, 0, 4, 1, 1)
        self.R1C1 = QtWidgets.QPushButton(self.backgrond)
        self.R1C1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R1C1.sizePolicy().hasHeightForWidth())
        self.R1C1.setSizePolicy(sizePolicy)
        self.R1C1.setMinimumSize(QtCore.QSize(50, 50))
        self.R1C1.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.R1C1.setText("")
        self.R1C1.setAutoRepeat(False)
        self.R1C1.setAutoExclusive(False)
        self.R1C1.setAutoDefault(False)
        self.R1C1.setDefault(False)
        self.R1C1.setFlat(False)
        self.R1C1.setObjectName("R1C1")
        self.button_layout.addWidget(self.R1C1, 0, 0, 1, 1)
        self.R2C5 = QtWidgets.QPushButton(self.backgrond)
        self.R2C5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R2C5.sizePolicy().hasHeightForWidth())
        self.R2C5.setSizePolicy(sizePolicy)
        self.R2C5.setMinimumSize(QtCore.QSize(50, 50))
        self.R2C5.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.R2C5.setText("")
        self.R2C5.setAutoRepeat(False)
        self.R2C5.setAutoExclusive(False)
        self.R2C5.setAutoDefault(False)
        self.R2C5.setDefault(False)
        self.R2C5.setFlat(False)
        self.R2C5.setObjectName("R2C5")
        self.button_layout.addWidget(self.R2C5, 1, 4, 1, 1)
        self.R3C1 = QtWidgets.QPushButton(self.backgrond)
        self.R3C1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R3C1.sizePolicy().hasHeightForWidth())
        self.R3C1.setSizePolicy(sizePolicy)
        self.R3C1.setMinimumSize(QtCore.QSize(50, 50))
        self.R3C1.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.R3C1.setText("")
        self.R3C1.setAutoRepeat(False)
        self.R3C1.setAutoExclusive(False)
        self.R3C1.setAutoDefault(False)
        self.R3C1.setDefault(False)
        self.R3C1.setFlat(False)
        self.R3C1.setObjectName("R3C1")
        self.button_layout.addWidget(self.R3C1, 2, 0, 1, 1)
        self.R1C2 = QtWidgets.QPushButton(self.backgrond)
        self.R1C2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R1C2.sizePolicy().hasHeightForWidth())
        self.R1C2.setSizePolicy(sizePolicy)
        self.R1C2.setMinimumSize(QtCore.QSize(50, 50))
        self.R1C2.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.R1C2.setText("")
        self.R1C2.setAutoRepeat(False)
        self.R1C2.setAutoExclusive(False)
        self.R1C2.setAutoDefault(False)
        self.R1C2.setDefault(False)
        self.R1C2.setFlat(False)
        self.R1C2.setObjectName("R1C2")
        self.button_layout.addWidget(self.R1C2, 0, 1, 1, 1)
        self.R1C3 = QtWidgets.QPushButton(self.backgrond)
        self.R1C3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R1C3.sizePolicy().hasHeightForWidth())
        self.R1C3.setSizePolicy(sizePolicy)
        self.R1C3.setMinimumSize(QtCore.QSize(50, 50))
        self.R1C3.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.R1C3.setText("")
        self.R1C3.setAutoRepeat(False)
        self.R1C3.setAutoExclusive(False)
        self.R1C3.setAutoDefault(False)
        self.R1C3.setDefault(False)
        self.R1C3.setFlat(False)
        self.R1C3.setObjectName("R1C3")
        self.button_layout.addWidget(self.R1C3, 0, 2, 1, 1)
        self.R1C4 = QtWidgets.QPushButton(self.backgrond)
        self.R1C4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R1C4.sizePolicy().hasHeightForWidth())
        self.R1C4.setSizePolicy(sizePolicy)
        self.R1C4.setMinimumSize(QtCore.QSize(50, 50))
        self.R1C4.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.R1C4.setText("")
        self.R1C4.setAutoRepeat(False)
        self.R1C4.setAutoExclusive(False)
        self.R1C4.setAutoDefault(False)
        self.R1C4.setDefault(False)
        self.R1C4.setFlat(False)
        self.R1C4.setObjectName("R1C4")
        self.button_layout.addWidget(self.R1C4, 0, 3, 1, 1)
        self.R2C1 = QtWidgets.QPushButton(self.backgrond)
        self.R2C1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R2C1.sizePolicy().hasHeightForWidth())
        self.R2C1.setSizePolicy(sizePolicy)
        self.R2C1.setMinimumSize(QtCore.QSize(50, 50))
        self.R2C1.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.R2C1.setText("")
        self.R2C1.setAutoRepeat(False)
        self.R2C1.setAutoExclusive(False)
        self.R2C1.setAutoDefault(False)
        self.R2C1.setDefault(False)
        self.R2C1.setFlat(False)
        self.R2C1.setObjectName("R2C1")
        self.button_layout.addWidget(self.R2C1, 1, 0, 1, 1)
        self.R2C2 = QtWidgets.QPushButton(self.backgrond)
        self.R2C2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R2C2.sizePolicy().hasHeightForWidth())
        self.R2C2.setSizePolicy(sizePolicy)
        self.R2C2.setMinimumSize(QtCore.QSize(50, 50))
        self.R2C2.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.R2C2.setText("")
        self.R2C2.setAutoRepeat(False)
        self.R2C2.setAutoExclusive(False)
        self.R2C2.setAutoDefault(False)
        self.R2C2.setDefault(False)
        self.R2C2.setFlat(False)
        self.R2C2.setObjectName("R2C2")
        self.button_layout.addWidget(self.R2C2, 1, 1, 1, 1)
        self.R2C3 = QtWidgets.QPushButton(self.backgrond)
        self.R2C3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R2C3.sizePolicy().hasHeightForWidth())
        self.R2C3.setSizePolicy(sizePolicy)
        self.R2C3.setMinimumSize(QtCore.QSize(50, 50))
        self.R2C3.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.R2C3.setText("")
        self.R2C3.setAutoRepeat(False)
        self.R2C3.setAutoExclusive(False)
        self.R2C3.setAutoDefault(False)
        self.R2C3.setDefault(False)
        self.R2C3.setFlat(False)
        self.R2C3.setObjectName("R2C3")
        self.button_layout.addWidget(self.R2C3, 1, 2, 1, 1)
        self.R2C4 = QtWidgets.QPushButton(self.backgrond)
        self.R2C4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R2C4.sizePolicy().hasHeightForWidth())
        self.R2C4.setSizePolicy(sizePolicy)
        self.R2C4.setMinimumSize(QtCore.QSize(50, 50))
        self.R2C4.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.R2C4.setText("")
        self.R2C4.setAutoRepeat(False)
        self.R2C4.setAutoExclusive(False)
        self.R2C4.setAutoDefault(False)
        self.R2C4.setDefault(False)
        self.R2C4.setFlat(False)
        self.R2C4.setObjectName("R2C4")
        self.button_layout.addWidget(self.R2C4, 1, 3, 1, 1)
        self.R5C1 = QtWidgets.QPushButton(self.backgrond)
        self.R5C1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R5C1.sizePolicy().hasHeightForWidth())
        self.R5C1.setSizePolicy(sizePolicy)
        self.R5C1.setMinimumSize(QtCore.QSize(50, 50))
        self.R5C1.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.R5C1.setText("")
        self.R5C1.setAutoRepeat(False)
        self.R5C1.setAutoExclusive(False)
        self.R5C1.setAutoDefault(False)
        self.R5C1.setDefault(False)
        self.R5C1.setFlat(False)
        self.R5C1.setObjectName("R5C1")
        self.button_layout.addWidget(self.R5C1, 4, 0, 1, 1)
        self.R5C4 = QtWidgets.QPushButton(self.backgrond)
        self.R5C4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R5C4.sizePolicy().hasHeightForWidth())
        self.R5C4.setSizePolicy(sizePolicy)
        self.R5C4.setMinimumSize(QtCore.QSize(50, 50))
        self.R5C4.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.R5C4.setText("")
        self.R5C4.setAutoRepeat(False)
        self.R5C4.setAutoExclusive(False)
        self.R5C4.setAutoDefault(False)
        self.R5C4.setDefault(False)
        self.R5C4.setFlat(False)
        self.R5C4.setObjectName("R5C4")
        self.button_layout.addWidget(self.R5C4, 4, 3, 1, 1)
        self.R3C4 = QtWidgets.QPushButton(self.backgrond)
        self.R3C4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R3C4.sizePolicy().hasHeightForWidth())
        self.R3C4.setSizePolicy(sizePolicy)
        self.R3C4.setMinimumSize(QtCore.QSize(50, 50))
        self.R3C4.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.R3C4.setText("")
        self.R3C4.setAutoRepeat(False)
        self.R3C4.setAutoExclusive(False)
        self.R3C4.setAutoDefault(False)
        self.R3C4.setDefault(False)
        self.R3C4.setFlat(False)
        self.R3C4.setObjectName("R3C4")
        self.button_layout.addWidget(self.R3C4, 2, 3, 1, 1)
        self.R4C2 = QtWidgets.QPushButton(self.backgrond)
        self.R4C2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R4C2.sizePolicy().hasHeightForWidth())
        self.R4C2.setSizePolicy(sizePolicy)
        self.R4C2.setMinimumSize(QtCore.QSize(50, 50))
        self.R4C2.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.R4C2.setText("")
        self.R4C2.setAutoRepeat(False)
        self.R4C2.setAutoExclusive(False)
        self.R4C2.setAutoDefault(False)
        self.R4C2.setDefault(False)
        self.R4C2.setFlat(False)
        self.R4C2.setObjectName("R4C2")
        self.button_layout.addWidget(self.R4C2, 3, 1, 1, 1)
        self.R5C3 = QtWidgets.QPushButton(self.backgrond)
        self.R5C3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R5C3.sizePolicy().hasHeightForWidth())
        self.R5C3.setSizePolicy(sizePolicy)
        self.R5C3.setMinimumSize(QtCore.QSize(50, 50))
        self.R5C3.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.R5C3.setText("")
        self.R5C3.setAutoRepeat(False)
        self.R5C3.setAutoExclusive(False)
        self.R5C3.setAutoDefault(False)
        self.R5C3.setDefault(False)
        self.R5C3.setFlat(False)
        self.R5C3.setObjectName("R5C3")
        self.button_layout.addWidget(self.R5C3, 4, 2, 1, 1)
        self.R3C3 = QtWidgets.QPushButton(self.backgrond)
        self.R3C3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R3C3.sizePolicy().hasHeightForWidth())
        self.R3C3.setSizePolicy(sizePolicy)
        self.R3C3.setMinimumSize(QtCore.QSize(50, 50))
        self.R3C3.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.R3C3.setText("")
        self.R3C3.setAutoRepeat(False)
        self.R3C3.setAutoExclusive(False)
        self.R3C3.setAutoDefault(False)
        self.R3C3.setDefault(False)
        self.R3C3.setFlat(False)
        self.R3C3.setObjectName("R3C3")
        self.button_layout.addWidget(self.R3C3, 2, 2, 1, 1)
        self.R3C5 = QtWidgets.QPushButton(self.backgrond)
        self.R3C5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R3C5.sizePolicy().hasHeightForWidth())
        self.R3C5.setSizePolicy(sizePolicy)
        self.R3C5.setMinimumSize(QtCore.QSize(50, 50))
        self.R3C5.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.R3C5.setText("")
        self.R3C5.setAutoRepeat(False)
        self.R3C5.setAutoExclusive(False)
        self.R3C5.setAutoDefault(False)
        self.R3C5.setDefault(False)
        self.R3C5.setFlat(False)
        self.R3C5.setObjectName("R3C5")
        self.button_layout.addWidget(self.R3C5, 2, 4, 1, 1)
        self.R3C2 = QtWidgets.QPushButton(self.backgrond)
        self.R3C2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R3C2.sizePolicy().hasHeightForWidth())
        self.R3C2.setSizePolicy(sizePolicy)
        self.R3C2.setMinimumSize(QtCore.QSize(50, 50))
        self.R3C2.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.R3C2.setText("")
        self.R3C2.setAutoRepeat(False)
        self.R3C2.setAutoExclusive(False)
        self.R3C2.setAutoDefault(False)
        self.R3C2.setDefault(False)
        self.R3C2.setFlat(False)
        self.R3C2.setObjectName("R3C2")
        self.button_layout.addWidget(self.R3C2, 2, 1, 1, 1)
        self.R4C4 = QtWidgets.QPushButton(self.backgrond)
        self.R4C4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R4C4.sizePolicy().hasHeightForWidth())
        self.R4C4.setSizePolicy(sizePolicy)
        self.R4C4.setMinimumSize(QtCore.QSize(50, 50))
        self.R4C4.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.R4C4.setText("")
        self.R4C4.setAutoRepeat(False)
        self.R4C4.setAutoExclusive(False)
        self.R4C4.setAutoDefault(False)
        self.R4C4.setDefault(False)
        self.R4C4.setFlat(False)
        self.R4C4.setObjectName("R4C4")
        self.button_layout.addWidget(self.R4C4, 3, 3, 1, 1)
        self.R5C2 = QtWidgets.QPushButton(self.backgrond)
        self.R5C2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R5C2.sizePolicy().hasHeightForWidth())
        self.R5C2.setSizePolicy(sizePolicy)
        self.R5C2.setMinimumSize(QtCore.QSize(50, 50))
        self.R5C2.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.R5C2.setText("")
        self.R5C2.setAutoRepeat(False)
        self.R5C2.setAutoExclusive(False)
        self.R5C2.setAutoDefault(False)
        self.R5C2.setDefault(False)
        self.R5C2.setFlat(False)
        self.R5C2.setObjectName("R5C2")
        self.button_layout.addWidget(self.R5C2, 4, 1, 1, 1)
        self.R4C3 = QtWidgets.QPushButton(self.backgrond)
        self.R4C3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R4C3.sizePolicy().hasHeightForWidth())
        self.R4C3.setSizePolicy(sizePolicy)
        self.R4C3.setMinimumSize(QtCore.QSize(50, 50))
        self.R4C3.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.R4C3.setText("")
        self.R4C3.setAutoRepeat(False)
        self.R4C3.setAutoExclusive(False)
        self.R4C3.setAutoDefault(False)
        self.R4C3.setDefault(False)
        self.R4C3.setFlat(False)
        self.R4C3.setObjectName("R4C3")
        self.button_layout.addWidget(self.R4C3, 3, 2, 1, 1)
        self.R4C1 = QtWidgets.QPushButton(self.backgrond)
        self.R4C1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R4C1.sizePolicy().hasHeightForWidth())
        self.R4C1.setSizePolicy(sizePolicy)
        self.R4C1.setMinimumSize(QtCore.QSize(50, 50))
        self.R4C1.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.R4C1.setText("")
        self.R4C1.setAutoRepeat(False)
        self.R4C1.setAutoExclusive(False)
        self.R4C1.setAutoDefault(False)
        self.R4C1.setDefault(False)
        self.R4C1.setFlat(False)
        self.R4C1.setObjectName("R4C1")
        self.button_layout.addWidget(self.R4C1, 3, 0, 1, 1)
        self.R5C5 = QtWidgets.QPushButton(self.backgrond)
        self.R5C5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R5C5.sizePolicy().hasHeightForWidth())
        self.R5C5.setSizePolicy(sizePolicy)
        self.R5C5.setMinimumSize(QtCore.QSize(50, 50))
        self.R5C5.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.R5C5.setText("")
        self.R5C5.setAutoRepeat(False)
        self.R5C5.setAutoExclusive(False)
        self.R5C5.setAutoDefault(False)
        self.R5C5.setDefault(False)
        self.R5C5.setFlat(False)
        self.R5C5.setObjectName("R5C5")
        self.button_layout.addWidget(self.R5C5, 4, 4, 1, 1)
        self.R4C5 = QtWidgets.QPushButton(self.backgrond)
        self.R4C5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R4C5.sizePolicy().hasHeightForWidth())
        self.R4C5.setSizePolicy(sizePolicy)
        self.R4C5.setMinimumSize(QtCore.QSize(50, 50))
        self.R4C5.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.R4C5.setText("")
        self.R4C5.setAutoRepeat(False)
        self.R4C5.setAutoExclusive(False)
        self.R4C5.setAutoDefault(False)
        self.R4C5.setDefault(False)
        self.R4C5.setFlat(False)
        self.R4C5.setObjectName("R4C5")
        self.button_layout.addWidget(self.R4C5, 3, 4, 1, 1)
        self.gridLayout_2.addLayout(self.button_layout, 1, 0, 1, 1)
        main.setCentralWidget(self.backgrond)
        self.actionquit = QtWidgets.QAction(main)
        self.actionquit.setObjectName("actionquit")

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "MainScence"))
        self.actionquit.setText(_translate("main", "quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main = QtWidgets.QMainWindow()
    ui = UiMain()
    ui.setupUi(main)
    main.show()
    sys.exit(app.exec_())

