# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Qt\UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class UiMain(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(1142, 758)
        self.backgrond = QtWidgets.QWidget(Main)
        self.backgrond.setObjectName("backgrond")
        self.backgrond_layout = QtWidgets.QHBoxLayout(self.backgrond)
        self.backgrond_layout.setContentsMargins(11, 11, 11, 11)
        self.backgrond_layout.setSpacing(6)
        self.backgrond_layout.setObjectName("backgrond_layout")
        self.C1 = QtWidgets.QVBoxLayout()
        self.C1.setSpacing(6)
        self.C1.setObjectName("C1")
        self.R1C1 = QtWidgets.QPushButton(self.backgrond)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R1C1.sizePolicy().hasHeightForWidth())
        self.R1C1.setSizePolicy(sizePolicy)
        self.R1C1.setMinimumSize(QtCore.QSize(0, 0))
        self.R1C1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.R1C1.setText("")
        self.R1C1.setObjectName("R1C1")
        self.C1.addWidget(self.R1C1)
        self.R2C1 = QtWidgets.QPushButton(self.backgrond)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R2C1.sizePolicy().hasHeightForWidth())
        self.R2C1.setSizePolicy(sizePolicy)
        self.R2C1.setMinimumSize(QtCore.QSize(0, 0))
        self.R2C1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.R2C1.setText("")
        self.R2C1.setObjectName("R2C1")
        self.C1.addWidget(self.R2C1)
        self.R3C1 = QtWidgets.QPushButton(self.backgrond)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R3C1.sizePolicy().hasHeightForWidth())
        self.R3C1.setSizePolicy(sizePolicy)
        self.R3C1.setMinimumSize(QtCore.QSize(0, 0))
        self.R3C1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.R3C1.setText("")
        self.R3C1.setObjectName("R3C1")
        self.C1.addWidget(self.R3C1)
        self.R4C1 = QtWidgets.QPushButton(self.backgrond)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R4C1.sizePolicy().hasHeightForWidth())
        self.R4C1.setSizePolicy(sizePolicy)
        self.R4C1.setMinimumSize(QtCore.QSize(0, 0))
        self.R4C1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.R4C1.setText("")
        self.R4C1.setObjectName("R4C1")
        self.C1.addWidget(self.R4C1)
        self.R5C1 = QtWidgets.QPushButton(self.backgrond)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R5C1.sizePolicy().hasHeightForWidth())
        self.R5C1.setSizePolicy(sizePolicy)
        self.R5C1.setMinimumSize(QtCore.QSize(0, 0))
        self.R5C1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.R5C1.setText("")
        self.R5C1.setObjectName("R5C1")
        self.C1.addWidget(self.R5C1)
        self.backgrond_layout.addLayout(self.C1)
        self.C2 = QtWidgets.QVBoxLayout()
        self.C2.setSpacing(6)
        self.C2.setObjectName("C2")
        self.R1C2 = QtWidgets.QPushButton(self.backgrond)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R1C2.sizePolicy().hasHeightForWidth())
        self.R1C2.setSizePolicy(sizePolicy)
        self.R1C2.setMinimumSize(QtCore.QSize(0, 0))
        self.R1C2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.R1C2.setText("")
        self.R1C2.setObjectName("R1C2")
        self.C2.addWidget(self.R1C2)
        self.R2C2 = QtWidgets.QPushButton(self.backgrond)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R2C2.sizePolicy().hasHeightForWidth())
        self.R2C2.setSizePolicy(sizePolicy)
        self.R2C2.setMinimumSize(QtCore.QSize(0, 0))
        self.R2C2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.R2C2.setText("")
        self.R2C2.setObjectName("R2C2")
        self.C2.addWidget(self.R2C2)
        self.R3C2 = QtWidgets.QPushButton(self.backgrond)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R3C2.sizePolicy().hasHeightForWidth())
        self.R3C2.setSizePolicy(sizePolicy)
        self.R3C2.setMinimumSize(QtCore.QSize(0, 0))
        self.R3C2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.R3C2.setText("")
        self.R3C2.setObjectName("R3C2")
        self.C2.addWidget(self.R3C2)
        self.R4C2 = QtWidgets.QPushButton(self.backgrond)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R4C2.sizePolicy().hasHeightForWidth())
        self.R4C2.setSizePolicy(sizePolicy)
        self.R4C2.setMinimumSize(QtCore.QSize(0, 0))
        self.R4C2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.R4C2.setText("")
        self.R4C2.setObjectName("R4C2")
        self.C2.addWidget(self.R4C2)
        self.R5C2 = QtWidgets.QPushButton(self.backgrond)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R5C2.sizePolicy().hasHeightForWidth())
        self.R5C2.setSizePolicy(sizePolicy)
        self.R5C2.setMinimumSize(QtCore.QSize(0, 0))
        self.R5C2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.R5C2.setText("")
        self.R5C2.setObjectName("R5C2")
        self.C2.addWidget(self.R5C2)
        self.backgrond_layout.addLayout(self.C2)
        self.C3 = QtWidgets.QVBoxLayout()
        self.C3.setSpacing(6)
        self.C3.setObjectName("C3")
        self.R1C3 = QtWidgets.QPushButton(self.backgrond)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R1C3.sizePolicy().hasHeightForWidth())
        self.R1C3.setSizePolicy(sizePolicy)
        self.R1C3.setMinimumSize(QtCore.QSize(0, 0))
        self.R1C3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.R1C3.setText("")
        self.R1C3.setObjectName("R1C3")
        self.C3.addWidget(self.R1C3)
        self.R2C3 = QtWidgets.QPushButton(self.backgrond)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R2C3.sizePolicy().hasHeightForWidth())
        self.R2C3.setSizePolicy(sizePolicy)
        self.R2C3.setMinimumSize(QtCore.QSize(0, 0))
        self.R2C3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.R2C3.setText("")
        self.R2C3.setObjectName("R2C3")
        self.C3.addWidget(self.R2C3)
        self.R3C3 = QtWidgets.QPushButton(self.backgrond)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R3C3.sizePolicy().hasHeightForWidth())
        self.R3C3.setSizePolicy(sizePolicy)
        self.R3C3.setMinimumSize(QtCore.QSize(0, 0))
        self.R3C3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.R3C3.setText("")
        self.R3C3.setObjectName("R3C3")
        self.C3.addWidget(self.R3C3)
        self.R4C3 = QtWidgets.QPushButton(self.backgrond)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R4C3.sizePolicy().hasHeightForWidth())
        self.R4C3.setSizePolicy(sizePolicy)
        self.R4C3.setMinimumSize(QtCore.QSize(0, 0))
        self.R4C3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.R4C3.setText("")
        self.R4C3.setObjectName("R4C3")
        self.C3.addWidget(self.R4C3)
        self.R5C3 = QtWidgets.QPushButton(self.backgrond)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R5C3.sizePolicy().hasHeightForWidth())
        self.R5C3.setSizePolicy(sizePolicy)
        self.R5C3.setMinimumSize(QtCore.QSize(0, 0))
        self.R5C3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.R5C3.setText("")
        self.R5C3.setObjectName("R5C3")
        self.C3.addWidget(self.R5C3)
        self.backgrond_layout.addLayout(self.C3)
        self.C4 = QtWidgets.QVBoxLayout()
        self.C4.setSpacing(6)
        self.C4.setObjectName("C4")
        self.R1C4 = QtWidgets.QPushButton(self.backgrond)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R1C4.sizePolicy().hasHeightForWidth())
        self.R1C4.setSizePolicy(sizePolicy)
        self.R1C4.setMinimumSize(QtCore.QSize(0, 0))
        self.R1C4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.R1C4.setText("")
        self.R1C4.setObjectName("R1C4")
        self.C4.addWidget(self.R1C4)
        self.R2C4 = QtWidgets.QPushButton(self.backgrond)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R2C4.sizePolicy().hasHeightForWidth())
        self.R2C4.setSizePolicy(sizePolicy)
        self.R2C4.setMinimumSize(QtCore.QSize(0, 0))
        self.R2C4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.R2C4.setText("")
        self.R2C4.setObjectName("R2C4")
        self.C4.addWidget(self.R2C4)
        self.R3C4 = QtWidgets.QPushButton(self.backgrond)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R3C4.sizePolicy().hasHeightForWidth())
        self.R3C4.setSizePolicy(sizePolicy)
        self.R3C4.setMinimumSize(QtCore.QSize(0, 0))
        self.R3C4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.R3C4.setText("")
        self.R3C4.setObjectName("R3C4")
        self.C4.addWidget(self.R3C4)
        self.R4C4 = QtWidgets.QPushButton(self.backgrond)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R4C4.sizePolicy().hasHeightForWidth())
        self.R4C4.setSizePolicy(sizePolicy)
        self.R4C4.setMinimumSize(QtCore.QSize(0, 0))
        self.R4C4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.R4C4.setText("")
        self.R4C4.setObjectName("R4C4")
        self.C4.addWidget(self.R4C4)
        self.R5C4 = QtWidgets.QPushButton(self.backgrond)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R5C4.sizePolicy().hasHeightForWidth())
        self.R5C4.setSizePolicy(sizePolicy)
        self.R5C4.setMinimumSize(QtCore.QSize(0, 0))
        self.R5C4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.R5C4.setText("")
        self.R5C4.setObjectName("R5C4")
        self.C4.addWidget(self.R5C4)
        self.backgrond_layout.addLayout(self.C4)
        self.C5 = QtWidgets.QVBoxLayout()
        self.C5.setSpacing(6)
        self.C5.setObjectName("C5")
        self.R1C5 = QtWidgets.QPushButton(self.backgrond)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R1C5.sizePolicy().hasHeightForWidth())
        self.R1C5.setSizePolicy(sizePolicy)
        self.R1C5.setMinimumSize(QtCore.QSize(0, 0))
        self.R1C5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.R1C5.setText("")
        self.R1C5.setObjectName("R1C5")
        self.C5.addWidget(self.R1C5)
        self.R2C5 = QtWidgets.QPushButton(self.backgrond)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R2C5.sizePolicy().hasHeightForWidth())
        self.R2C5.setSizePolicy(sizePolicy)
        self.R2C5.setMinimumSize(QtCore.QSize(0, 0))
        self.R2C5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.R2C5.setText("")
        self.R2C5.setObjectName("R2C5")
        self.C5.addWidget(self.R2C5)
        self.R3C5 = QtWidgets.QPushButton(self.backgrond)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R3C5.sizePolicy().hasHeightForWidth())
        self.R3C5.setSizePolicy(sizePolicy)
        self.R3C5.setMinimumSize(QtCore.QSize(0, 0))
        self.R3C5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.R3C5.setText("")
        self.R3C5.setObjectName("R3C5")
        self.C5.addWidget(self.R3C5)
        self.R4C5 = QtWidgets.QPushButton(self.backgrond)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R4C5.sizePolicy().hasHeightForWidth())
        self.R4C5.setSizePolicy(sizePolicy)
        self.R4C5.setMinimumSize(QtCore.QSize(0, 0))
        self.R4C5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.R4C5.setText("")
        self.R4C5.setObjectName("R4C5")
        self.C5.addWidget(self.R4C5)
        self.R5C5 = QtWidgets.QPushButton(self.backgrond)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R5C5.sizePolicy().hasHeightForWidth())
        self.R5C5.setSizePolicy(sizePolicy)
        self.R5C5.setMinimumSize(QtCore.QSize(0, 0))
        self.R5C5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.R5C5.setText("")
        self.R5C5.setObjectName("R5C5")
        self.C5.addWidget(self.R5C5)
        self.backgrond_layout.addLayout(self.C5)
        Main.setCentralWidget(self.backgrond)
        self.actionquit = QtWidgets.QAction(Main)
        self.actionquit.setObjectName("actionquit")

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)
        Main.setTabOrder(self.R1C1, self.R1C2)
        Main.setTabOrder(self.R1C2, self.R1C3)
        Main.setTabOrder(self.R1C3, self.R1C4)
        Main.setTabOrder(self.R1C4, self.R1C5)
        Main.setTabOrder(self.R1C5, self.R2C1)
        Main.setTabOrder(self.R2C1, self.R2C2)
        Main.setTabOrder(self.R2C2, self.R2C3)
        Main.setTabOrder(self.R2C3, self.R2C4)
        Main.setTabOrder(self.R2C4, self.R2C5)
        Main.setTabOrder(self.R2C5, self.R3C1)
        Main.setTabOrder(self.R3C1, self.R3C2)
        Main.setTabOrder(self.R3C2, self.R3C3)
        Main.setTabOrder(self.R3C3, self.R3C4)
        Main.setTabOrder(self.R3C4, self.R3C5)
        Main.setTabOrder(self.R3C5, self.R4C1)
        Main.setTabOrder(self.R4C1, self.R4C2)
        Main.setTabOrder(self.R4C2, self.R4C3)
        Main.setTabOrder(self.R4C3, self.R4C4)
        Main.setTabOrder(self.R4C4, self.R4C5)
        Main.setTabOrder(self.R4C5, self.R5C1)
        Main.setTabOrder(self.R5C1, self.R5C2)
        Main.setTabOrder(self.R5C2, self.R5C3)
        Main.setTabOrder(self.R5C3, self.R5C4)
        Main.setTabOrder(self.R5C4, self.R5C5)
        Main.setTabOrder(self.R5C5, self.R1C1)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "MainScence"))
        self.actionquit.setText(_translate("Main", "quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QMainWindow()
    ui = UiMain()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())

